# Generated by Django 5.2.12 on 2026-03-26 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show in homepage carousel'),
        ),
        migrations.CreateModel(
            name='FeaturedSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('subtitle', models.CharField(blank=True, max_length=250)),
                ('image', models.ImageField(upload_to='carousel')),
                ('custom_url', models.CharField(blank=True, help_text='Used only when no product is selected', max_length=500)),
                ('cta_text', models.CharField(default='Shop Now', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(blank=True, help_text='Link slide to this product (leave blank to use custom URL)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slides', to='shop.product')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
